# Generated by Django 6.1 on 2026-08-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_document_file',
            field=models.FileField(default=1, upload_to='uploads/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
