# Generated by Django 6.1 on 2026-08-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_featured_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='featured_document_file',
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=20),
        ),
    ]
