# Generated by Django 6.1 on 2026-08-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_about_socialmedialinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='SocialMediaLinks',
        ),
    ]
